config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index", as: :home
  get "/admin", to: "sessions#show"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  get "/date", to: "order#date"
  get "/date_display", to: "order#date_display"
  resources :users
  resources :menu
  resources :menu_items
  resources :order
  resources :order_items
  resources :cart_items
  delete "/signout", to: "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  def self.update(id, quantity)
    cart_item = CartItem.find(id)
    cart_item.item_quantity = quantity
    cart_item.save!
  end

  def self.cart_id(item_id)
    CartItem.find_by(menu_item_id: item_id).id
  end
  def self.quantity(item_id)
    CartItem.find_by(menu_item_id: item_id).item_quantity
  end
  def self.amount
    amount = 0
    CartItem.all.each do |cart_item|
      amount += cart_item.cart_item_price * cart_item.item_quantity
    end
    amount
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :menu_items
  class << self; attr_accessor :j, :edit end
  @j = 12
  @edit = nil
  def self.menu
    menus = Array.new
    Menu.all.each do |menu|
      menus.push(menu) if Menu.exists? id: menu.id
    end
    @active_menus = Array.new
    for i in 0..menus.size - 1
      next if i.odd?
      menu = Array.new
      menu.push(menus[i])
      menu.push(menus[i + 1])
      @active_menus.push(menu)
    end
    @active_menus
  end
  def self.item(i)
    @j = i
  end
  def self.no
    @j
  end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
  class << self; attr_accessor :no, :edit end
  @no = nil
  @edit = nil

  def self.menu_items(id)
    MenuItem.where(menu_id: id)
  end

  def self.active_menus
    menus = Array.new
    Menu.all.each do |menu|
      if menu.id != no
        menus.push(menu)
      end
    end
    menus
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def self.pl
    OrderItem.create!(order_id: 1, menu_item_id: 1,
                      menu_item_name: "l",
                      quantity: 4)
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menu_item
  def self.active_order_items(order_no)
    CartItem.all.each do |cart_item|
      OrderItem.create!(order_id: order_no, menu_item_id: cart_item.menu_item_id,
                        menu_item_name: cart_item.cart_menu_item,
                        quantity: cart_item.item_quantity)
    end
    CartItem.destroy_all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    if CartItem.exists? menu_item_id: params[:menu_item_id]
      cart_item = CartItem.find(CartItem.find_by(menu_item_id: params[:menu_item_id]).id)
      cart_item.item_quantity = params[:quantity]
      cart_item.save!
    else
      new_cart_item = CartItem.create!(menu_item_id: params[:menu_item_id],
                                       cart_item: params[:menu_item],
                                       cart_item_price: params[:price],
                                       item_quantity: 1)
      menu_id = MenuItem.find(params[:menu_item_id]).menu_id
    end
    redirect_to "/menu##{Menu.find(menu_id).menu_name}"
  end

  def update
    cart_item = CartItem.find(params[:id])
    if params[:state]
      cart_item.item_quantity += 1
      cart_item.save!
    else
      cart_item.item_quantity -= 1
      cart_item.save!

      if cart_item.item_quantity == 0
        CartItem.find(params[:id]).destroy
      end
    end
    menu_item = MenuItem.find(cart_item.menu_item_id)
    redirect_to "/menu/##{Menu.find(menu_item.menu_id).menu_name}"
  end

  def destroy
    CartItem.find(params[:id]).destroy

    redirect_to cart_items_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def new
    @id = params[:menu_id]
    @m_id = params[:menuitem_edit_id]
  end

  def index
  end

  def show
    edit_id = params[:id]
    @menu = Menu.find(edit_id)
  end

  def create
    new_menu = Menu.create!(menu_name: params[:menu_name])
    redirect_to "/menu/new"
  end

  def update
    menu = Menu.find(params[:id])
    menu.menu_name = params[:new_menu_name]
    menu.save!
    redirect_to "/menu/new?menu_id=#{menu.id}"
  end

  def destroy
    menuitems = MenuItem.all.where(menu_id: params[:id])
    menu = Menu.find(params[:id])
    menuitems.destroy_all
    menu.destroy
    redirect_to "/menu/new"
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    edit_id = params[:edit]
    @menu_item = MenuItem.find(edit_id)
  end

  def show
    edit_id = params[:edit]
    @menu_item = MenuItem.find(edit_id)
  end

  def new
  end

  def create
    new_menu_item = params[:menu_item]
    price = params[:price]
    menu_id = params[:menu_id]
    MenuItem.create!(menu_item: new_menu_item, description: nil, price: price, menu_id: menu_id)
    redirect_to "/menu/new"
  end

  def create1
    id = params[:menu_no]
    MenuItem.no = id
    redirect_to "/menu_items/new"
  end

  def update
    menuitem = MenuItem.find(params[:id])
    menuitem.menu_item = params[:new_menuitem_name]
    menuitem.price = params[:new_menuitem_price]
    menuitem.menu_id = params[:new_menuitem_menu_id]
    menuitem.save!
    redirect_to "/menu/new?menu_id=#{menuitem.menu_id}"
  end

  def destroy
    menuitem = MenuItem.find(params[:delete])
    menuitem.destroy
    redirect_to "/menu/new?menu_id=#{menuitem.menu_id}"
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    new_order = Order.create!(user_id: 1,
                              order_date: Date.today,
                              amount: 30)
    OrderItem.active_order_items(new_order.id)
    redirect_to "/order"
  end

  def date
  end

  def date_display
    @start = params[:start_date]
    @end = params[:end_date]
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    new_order_item = OrderItem.create!(menu_item_id: params[:menu_item_id],
                                       order_id: params[:order_id],
                                       menu_item_name: params[:menu_item],
                                       quantity: params[:quantity])
    redirect_to "/menu"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render "new"
  end

  def create
  end

  def show
    render "show"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render "new"
  end

  def create
    new_user = User.create!(first_name: params[:first_name],
                            last_name: params[:last_name],
                            email: params[:email],
                            password: params[:password])
  end

  def show
    render "show"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart_items/_form-section.html.erb
<form method="get" action= <%=form_action%> method=<%= form_method%>>
    <button class="MenuBar-button" type="submit"><%=form_value%> </button>
</form>

app/views/cart_items/index.html.erb
 <div class="MenuBar">
<%= render partial: "form-section" ,locals:{form_action: "/menu" ,form_value: "Menus",form_method: "GET" }%>
<form method="get" action="/users/1" method="GET">
    <button class="MenuBar-button" type="submit">My account </button>
</form>
<p class="User-credentials"> Hello! User </p>
<form method="get" action="/cart_items" method="GET">
    <button  class="MenuBar-button" type="submit">View Cart</button>
</form>
<%= render partial: "form-section" ,locals:{  form_action: "/order" , form_value: "My Orders",form_method: "GET" }%>

<%= render partial: "form-section" ,locals:{  form_action: "/signout" ,form_value: "SignOut", form_method: "Delete" }%>
</div>

<div class="Menus">


<hr class="Cafeteria-header-line">
  <h1 class="MenuPageTitle">Cart</h1>


</div>


<table class="OrderCart">
	<thead>
	<tr>
		<th>S No.</th>
		<th>Items</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Total</th>
		<th>action</th>
	</tr>

	</thead>
	<tbody>
	<% CartItem.all.each_with_index do |cart_item,i|%>
	<tr>
		<td><%= i+1	 %> </td>
		<td> <%= cart_item.cart_item%> </td>
		<td> <%= cart_item.cart_item_price%> </td>
		<td> <%= cart_item.item_quantity %> </td>
		<td> <%= cart_item.item_quantity * cart_item.cart_item_price %> </td>
		<td>
				<%= link_to "remove", "/cart_items/#{cart_item.id}" ,method: "delete" %>
		</td>
	</tr>
	<% end %>
	</tbody>
</table>
<h2 class="OrderDetails-title">Amount:</h2>
<p><%= CartItem.amount %></p>
<section class="OrderDetails">
  <div class="OrderType">
  	<h2 class="OrderDetails-title">Select Order Type:</h2>
    	<select id="Payment-type" name="Payment-type">
   		 <option value="Cash">Dine-In</option>
   		 <option value="Google pay">Pick-up</option>
   		 <option value="EatUp Wallet">Delivery</option>
 		 </select>
 	 </div>
	<form  action= "/order" method="POST">
          <input  class="OrderButton" type="submit" value="Place Order" >
</form>

</section>
<img src="order.png" alt="Order" class="OrderBanner">

app/views/home/index.html.erb
 <h1 class ="Cafeteria-title">Made with Love</h1>
  <p class="Cafeteria-authenticate">Don't have an account yet ? <%= link_to "Sign up", new_user_path %> </p>
  <p class="Cafeteria-authenticate"> Have an account just <%= link_to "Sign in", new_sessions_path %> with your Eat'Up-account</p>

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <h2>For more information about Eat-up</h2>
    <h3>Mail us at &nbsp
      <span>gvkprasad2001@gmail.com &nbsp</span>
      and &nbsp
      <span>dinesh@gmail.com</span></h3>
  </div>
  <hr>
  <div>
    Connect:
    <address>
      <p>
        Eat-up,2
        <sup>nd</sup>
        floor,Star-city Mall
        <br>
        wild-west street,Amsterdam.
      </p>
      <p>
        Reach us at
        <a href="https://www.youtube.com/watch?v=QcIy9NiNbmo">Eat-up.co</a>
        .
      </p>
    </address>
  <div>
  <hr>
    &copy; Eat-up.com | Designed by dinesh and kp
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafeteria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
  <div class="Cafeteria-header"  >
      <img class="Cafeteria-logo" src="logo.png">
        <h1 class="Cafeteria-title ">Welcome to EAT'UP Cafeteria</h1>
      <hr class="Cafeteria-header-line">
  </div>
    <% if flash[:error] %>
      <p class="Flash-error"> <%= flash[:error]%></p>
    <% end %>
  <div class="Cafeteria" >

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

      <%= yield %>
    <hr>
    <%= render "layouts/footer" %>
  </div>


  </body>
</html>

app/views/menu/_form-section.html.erb
<form method="get" action= <%=form_action%> method=<%= form_method%>>
    <button class="MenuBar-button" type="submit"><%=form_value%> </button>
</form>

app/views/menu/_menu-section.html.erb
<section class="MenuSection">
  <h1 id="<%= section_title %>" class="MenuSection-title"> <%= section_title %> </h1>
    <ul class="MenuItem">
      <% menu_items.each do |menu_item| %>
        <li class="MenuItem-list">
           <label class="MenuItem-container">
             <%= menu_item.menu_item %>
              <p class="MenuItem-price"> Rs. <%=menu_item.price %></p>

             <%  if CartItem.exists? menu_item_id: menu_item.id  and  CartItem.find(CartItem.cart_id(menu_item.id)).item_quantity!=0  %>
<%k=CartItem.quantity(menu_item.id)%>
              <%=form_with(url: "/cart_items/#{CartItem.cart_id(menu_item.id)}", method: "put")do%>

               <input type="submit" class="CounterButton"  value="-" >
              <% end %>
              <input class="MenuItem-quantity" type="integer" value="<%= k %>"max=10 name="quantity" disabled >

              <%=form_with(url: "/cart_items/#{CartItem.cart_id(menu_item.id)}", method: "put")do%>
                 <input type="hidden" name="state" value= "true"/>
                  <input type="submit" class="CounterButton" value="+" >
              <% end %>
             <% else%>
             <form  action= "/cart_items" method="POST">
              <input type="hidden" name="menu_item_id" value= <%= menu_item.id %> />
              <input type="hidden" name="menu_item" value= "<%= menu_item.menu_item %>" />
              <input type="hidden" name="price" value= <%= menu_item.price %> />
              <input class="AddButton" type="submit" value="Add" >
              </form>
             <% end %>
          </label>

      </li>

   <% end %>
          </ul>
  </section>

app/views/menu/index.html.erb
<article class="MenuPage">
  <div class="MenuBar">
<%= render partial: "form-section" ,locals:{form_action: "/menu" ,form_value: "Menus",form_method: "GET" }%>
<form method="get" action="/users/1" method="GET">
    <button class="MenuBar-button" type="submit">My account </button>
</form>
<p class="User-credentials"> Hello! User </p>
<form method="get" action="/cart_items" method="GET">
    <button  class="MenuBar-button" type="submit">View Cart</button>
</form>
<%= render partial: "form-section" ,locals:{  form_action: "/order" , form_value: "My Orders",form_method: "GET" }%>

<%= render partial: "form-section" ,locals:{  form_action: "/signout" ,form_value: "SignOut", form_method: "Delete" }%>
</div>

<div class="Menus">
  <hr class="Cafeteria-header-line">
  <h1 class="MenuPageTitle">MENUS</h1>
</div>
<div class="MenuContent">
  <div >
    <img class="MenuContent-image" src="food.jpg">
  </div>
  <div>
    <% Menu.menu.each do |menu| %>
    <div class="Menu">
      <%= render partial: "menu-section" ,locals:{section_title: menu[0].menu_name , menu_items: MenuItem.menu_items(menu[0].id) }%>
      <% if menu[1] %>
       <%= render partial: "menu-section" ,locals:{  section_title: menu[1].menu_name , menu_items: MenuItem.menu_items(menu[1].id) }%>
      <%end %>
    </div>
    <% end %>
    <form method="get" action="/cart_items" method="GET">
      <button class="CartButton button1"type="submit">Go to Cart</button>
    </form>
  </div>
</div>
</article>

app/views/menu/new.html.erb
<div class="Admin">
  <h1 class="Admin-title">ADMIN</h1>
</div>
<div class="NewMenu">
  <div class="Dash" >
    <form method="get" action="/users/1" method="GET">
      <button class="Dash-button" type="submit">DASHBOARD </button>
    </form>
    <form method="get" action="/menu/new" method="GET">
      <button class="Dash-button" type="submit">Manage Menus </button>
    </form>
    <form method="get" action="/users/1" method="GET">
      <button class="Dash-button" type="submit">Manage Users </button>
    </form>
    <form method="get" action="/users/1" method="GET">
      <button class="Dash-button" type="submit">Manage Orders</button>
    </form>
    <form method="get" action="/users/1" method="GET">
      <button class="Dash-button" type="submit">My account </button>
    </form>
  </div>
  <article class="AdminControl">

  <a href="#test">Section</a>

    <section class="AdminControl-section">
      <h2 class="MenuSection-title">Add Menu:</h2>
      <%= form_with(url: "/menu", method: "post") do%>
        <div>
          <label>Menu Name:</label>
          <input type="text", name="menu_name", placeholder="New menu name" >
        </div>
        <input type="submit", value="Add">
      <% end %>
    </section>

    <section class="AdminControl-section">
      <h2 class="MenuSection-title">New Menu-Item:</h2>
      <%= form_with(url: "/menu_items", method: "post") do%>
        Select Menu Type :
        <select name="menu_id">
          <% Menu.all.each do |menu| %>
            <option value="<%= menu.id %>"><%= menu.menu_name %></option>
          <% end %>
        </select>

        <div>
          Item name:
          <input type="text", name="menu_item", placeholder="New item name" >
        </div>
        <div>
          Item price: $
          <input type="integer", name="price" , placeholder=" price" >
        </div>
        <input type="submit", value="Add" >
      <% end %>
    </section>

    <section class="AdminControl-section">
      <h2 class="MenuSection-title">Edit:</h2>
      <%= form_with(url: "/menu/new#test", method: "get") do %>
        Select Menu Type :
        <select name="menu_id">
          <option value="false">--select-menu--</option>
          <% Menu.all.each do |menu| %>
            <option value="<%= menu.id %>"><%= menu.menu_name %></option>
          <% end %>
        </select>
        <input type="button", value="Get", Onclick="this.form.submit()" >
      <% end %>
      <% if @id %>
      <div id="test" class="MenuItem-container">
        <h1 class="MenuSection-title"> <%= Menu.find(@id).menu_name %> </h1>
        <%= link_to(menu_path(@id), method: "get") do %>
          <%= content_tag("i",nil,class:  "fa fa-edit") %>
        <% end %>
        <%= link_to(menu_path(@id), method: "delete") do %>
          <%= content_tag("i",nil,class:  "fa fa-trash") %>
        <% end %>
      </div>
        <ul class="MenuItem">
          <% MenuItem.where(menu_id: @id).each do |menu_item| %>
            <li class="MenuItem-list">
              <label class="MenuItem-container">
                <p><%=menu_item.menu_item %></p>
                <p class="MenuItem-price"> Rs. <%= menu_item.price %></p>
                <%= form_with(url: "/menu_items/#{menu_item.id}", method: "get") do %>
                  <input type="hidden" name="edit" value="<%= menu_item.id %>">
                  <input class="AddButton" type="button" Onclick="this.form.submit()" value="Edit">
                <% end %>
                <%= form_with(url: "/menu_items/#{menu_item.id}", method: "delete") do %>
                  <input type="hidden" name="delete" value="<%= menu_item.id %>">
                  <input class="AddButton" type="button" Onclick="this.form.submit()" value="Delete" >
                <% end %>
              </label>
            </li>
          <% end %>
        </ul>
      <% end %>
    </section>
  </article>
</div>

app/views/menu/show.html.erb
<p><%= @menu.id %></p>
<div class="EditMenuPage">
  <p class="EditMenu-title">Edit Menu</p>
  <section class="EditMenu">
    <%= form_with(url: "/menu/#{@menu.id}", method: "patch") do %>
      <div class="Form-section">
        <p class="Form-section-label">Menu</p>
        <input type="text" name="new_menu_name" value="<%= @menu.menu_name %>">
      </div>
      <div class="Form-section">
        <input type="button" Onclick="this.form.submit()" value="Update" >
      </div>
   <%end%>
  </section>
</div>

app/views/menu_items/index.html.erb
<p><%= @menu_item.id %></p>
<div class="NewUsersPage">
  <p class="NewUsers-title">Edit Menu-Item</p>
  <section class="UsersNew">
    <%= form_with(url: "/menu_items/#{@menu_item.id}", method: "patch") do %>
      <div class="Form-section">
        <p class="Form-section-label">Menu-Item</p>
        <input type="text" name="new_menuitem_name" value="<%= @menu_item.menu_item %>">
      </div>
      <div class="Form-section">
        <p class="Form-section-label">Price</p>
        <input type="text" name="new_menuitem_price" value="<%= @menu_item.price %>">
      </div>
      Select Menu Type :
      <select name="new_menuitem_menu_id">
        <% Menu.all.each do |menu| %>
          <option value="<%= menu.id %>"><%= menu.menu_name %></option>
        <% end %>
      </select>
      <div class="Form-section">
        <input type="button" Onclick="this.form.submit()" value="Update" >
      </div>
   <%end%>
  </section>
</div>

app/views/menu_items/new.html.erb
<p><%= @k=MenuItem.no %></p>

<form  action="/menu_items" method="get">

  Select your favorite menu:

  <select id="mySelect" name="menu_no" >


  <% if MenuItem.no %>
<p><%= MenuItem.no %></p>
 <option> <%= Menu.find(MenuItem.no).menu_name%> </option>
 <option>--select Menu--  </option>
<% else %>
  <option> --select Menu-- </option>

<% end %>
<% MenuItem.active_menus.each do |menu| %>


  <option type= "button" name="menu_no" onclick= "this.form.submit()" value= "<%= menu.id %>" > <%= menu.menu_name%> </option>



    <% end%>
  </select>

</form>
<% if MenuItem.no %>
<p><%= MenuItem.no %></p>
<% else %>
<p>k</p>

<% end %>
<form>
  Select your favorite fruit:
  <select id="mySelect" name="menu_no" >
  <option> ---Select Menu Items--- </option>
<% MenuItem.menu_items(MenuItem.no).each do |menu| %>
    <option  value= "<%= menu.id %>" > <%= menu.menu_item%> </option>

    <% end%>
  </select>
</form>

app/views/menu_items/show.html.erb
<div class="EditMenuPage">
  <p class="EditMenu-title">Edit Menu-Item</p>
  <section class="EditMenu">
    <%= form_with(url: "/menu_items/#{@menu_item.id}", method: "patch") do %>
      <div class="Form-section">
        <p class="Form-section-label">Menu-Item</p>
        <input type="text" name="new_menuitem_name" value="<%= @menu_item.menu_item %>">
      </div>
      <div class="Form-section">
        <p class="Form-section-label">Price</p>
        <input type="text" name="new_menuitem_price" value="<%= @menu_item.price %>">
      </div>
      <div class="Form-section">
        Select Menu Type :
        <select name="new_menuitem_menu_id">
          <% Menu.all.each do |menu| %>
            <option value="<%= menu.id %>"><%= menu.menu_name %></option>
          <% end %>
        </select>
      </div>
      <div class="Form-section">
        <input type="button" Onclick="this.form.submit()" value="Update" >
      </div>
   <%end%>
  </section>
</div>

app/views/order/_form-section.html.erb
<form method="get" action= <%=form_action%> method=<%= form_method%>>
    <button class="MenuBar-button" type="submit"><%=form_value%> </button>
</form>

app/views/order/date.html.erb
<%= form_with(url: "/date_display", method: "get") do %>
  Start date:
  <%= date_field_tag('start_date',nil) %>
  End date:
  <%= date_field_tag('end_date',nil) %>
    <input type="button", value="Get", Onclick="this.form.submit()" >
<% end %>

app/views/order/date_display.html.erb
This is in date_display
<p><%= @start %></p>
<p><%= @end %></p>

app/views/order/index.html.erb
 <div class="MenuBar">
<%= render partial: "form-section" ,locals:{form_action: "/menu" ,form_value: "Menus",form_method: "GET" }%>
<form method="get" action="/users/1" method="GET">
    <button class="MenuBar-button" type="submit">My account </button>
</form>
<p class="User-credentials"> Hello! User </p>
<form method="get" action="/cart_items" method="GET">
    <button  class="MenuBar-button" type="submit">View Cart</button>
</form>
<%= render partial: "form-section" ,locals:{  form_action: "/order" , form_value: "My Orders",form_method: "GET" }%>

<%= render partial: "form-section" ,locals:{  form_action: "/signout" ,form_value: "SignOut", form_method: "Delete" }%>
</div>


<div class="Menus">


<hr class="Cafeteria-header-line">
  <h1 class="MenuPageTitle">My Orders</h1>


</div>

<table class="OrderCart">

	<thead>
	<tr>
		<th>S No.</th>
		<th>Date</th>
		<th>Order-Id</th>
		<th>Amount</th>
		<th>Status</th>
	<th>Action</th>
	</tr>
	<tr>
		<td>1</td>
		<td>20-03-2001</td>
		<td>1990</td>
		<td>300</td>
    <td>Not Delivered</td>
		<td><%= link_to "Expand", "/cart_items" ,method: "get" %></td>
	</tr>	</thead>
	<tbody>

	</tbody>
</table>

app/views/users/_form-section.html.erb
<form method="get" action= <%=form_action%> method=<%= form_method%>>
    <button class="MenuBar-button" type="submit"><%=form_value%> </button>
</form>

app/views/users/new.html.erb
<div class="NewUsersPage">
  <p class="NewUsers-title">Create an account</p>
  <section class="UsersNew">
    <%=form_with url: users_path do |form| %>
      <div class="Form-section">
        <p class="Form-section-label">First Name</p>
        <%= form.text_field :first_name , class: "Form-section-input" ,placeholder: "First Name"%>
      </div>
      <div class="Form-section">
        <p class="Form-section-label">Last Name</p>
        <%= form.text_field :last_name , class: "Form-section-input",placeholder: "Last Name"%>
      </div>
      <div class="Form-section">
        <p class="Form-section-label">Email Address</p>
        <%= form.email_field :email , class: "Form-section-input",placeholder: "Email"%>
      </div>
      <div class="Form-section">
        <p class="Form-section-label">Password</p>
        <%= form.password_field :password , class: "Form-section-input",placeholder: "Password"%>
      </div>
      <div class="Form-section">
        <%= form.submit "Sign-up!" , class: "Form-section-submit"%>
      </div>
   <%end%>
  </section>
</div>

app/views/users/show.html.erb
 <div class="MenuBar">
<%= render partial: "form-section" ,locals:{form_action: "/menu" ,form_value: "Menus",form_method: "GET" }%>
<form method="get" action="/users/1" method="GET">
    <button class="MenuBar-button" type="submit">My account </button>
</form>
<p class="User-credentials"> Hello! User </p>
<form method="get" action="/cart_items" method="GET">
    <button  class="MenuBar-button" type="submit">View Cart</button>
</form>
<%= render partial: "form-section" ,locals:{  form_action: "/order" , form_value: "My Orders",form_method: "GET" }%>

<%= render partial: "form-section" ,locals:{  form_action: "/signout" ,form_value: "SignOut", form_method: "Delete" }%>
</div>
<div class="Menus">


<hr class="Cafeteria-header-line">
  <h1 class="MenuPageTitle">My account</h1>


</div>
<article class="Account">
  <h1 class="Account-header">Hello User</h1>
  <section>
    <ul>
      <li class="Details-item">
        <label class="Details-label">Name :</label>
        <input name="User_name" placeholder="Paritala Dinesh Kumar" disabled>
      </li>
      <li class="Details-item">
        <label class="Details-label">Gender :</label>
        <div class="Gender-options">
          <input type="radio" id="male" name="gender" value="male">
          <label for="male">Male</label><br>
          <input type="radio" id="female" name="gender" value="female">
          <label for="female">Female</label><br>
          <input type="radio" id="other" name="gender" value="other">
          <label for="other">Other</label>
        </div>
      </li>
      <li class="Details-item">
        <label class="Details-label">Date-of-Birth :</label>
        <%= date_field_tag(nil,nil,class: 'date-of-birth'   ) %>
      </li>
      <li class="Details-item">
        <label class="Details-label">Contact no :</label>
        <input name="User_mobile" placeholder="your contact number">
      </li>
      <li class="Details-item">
        <label class="Details-label">Mail ID :</label>
        <input name="User_mail" placeholder="ex:abc123@gmail.com">
      </li>
      <li class="Details-item">
        <label class="Details-label">Password :</label>
        <input name="User_password" placeholder="Password!">
      </li>
    </ul>
  </section>
</article>